server:
  port: 8001

spring:
  application:
    name: autenticacion-service
  main:
    allow-bean-definition-overriding: true

storage:
  conexion: ${AZURE_STORAGE_TABLE_ENDPOINT:TableEndpoint=https://expdigstorage.table.core.windows.net/;SharedAccessSignature=sv=2020-02-10&ss=bfqt&srt=sco&sp=rwdlacuptfx&se=2022-06-25T00:48:40Z&st=2021-06-24T16:48:40Z&spr=https&sig=tKEz6vo74SQzV27P09TKr%2F42oUOAbjF54Tc5vBjyosg%3D}
oauth:
  client-id: clinica-internacional
  client-secret: secret
  grant-types: password,authorization_code,refresh_token
  access-token-validity: 43200 #24 horas
  secret-token-validity: 2592000 #30 dias

microservices:
  clinicalrecord: ${HOST_CLINICALRECORD_SERVICE:http://localhost:8002}/v1
  document: ${HOST_DOCUMENT_SERVICE:http://localhost:8004}/v1/documento
  expediente: ${HOST_EXPEDIENTE_SERVICE:http://localhost:8003}/v1/expediente
  reporte: ${HOST_REPORTE_SERVICE:http://localhost:8085}/v1/reporte

azure:
  application-insights:
    instrumentation-key: ${AZURE_INSTRUMENTATION_KEY:4f2804e0-1ff1-4a86-b615-294c9cc7d166}

logbook:
  format.style : json
  exclude: [/v3/**]
  write.max-body-size: 1024

logging.level.org:
  zalando.logbook: INFO
  springframework: INFO